import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { connectDB } from '../config/db.js';
import mongoose from 'mongoose';
import User from '../models/User.js'; import College from '../models/College.js'; import Course from '../models/Course.js'; import CollegeCourse from '../models/CollegeCourse.js'; import CollegePlacement from '../models/CollegePlacement.js'; import CollegeFee from '../models/CollegeFee.js'; import CampusFacility from '../models/CampusFacility.js';

const names=['Apex Institute of Technology','Sunrise College of Computer Studies','Riverfront University College','Greenfield Institute','Western Valley College','Pioneer Arts and Commerce College','Metro School of Management','Silverline Institute','Knowledge Hub College','Cityview College'];
const courseData=[['BCA','BCA','UG','3 Years'],['BBA','BBA','UG','3 Years'],['B.Com','BCOM','UG','3 Years'],['B.Sc IT','BSCIT','UG','3 Years'],['B.Sc Computer Science','BSCCS','UG','3 Years'],['B.Tech Computer Science','BTCS','UG','4 Years'],['MCA','MCA','PG','2 Years'],['MBA','MBA','PG','2 Years'],['B.Sc Data Science','BSCDS','UG','3 Years'],['B.Sc Cyber Security','BSCCY','UG','3 Years']];
async function seed(){await connectDB(); await Promise.all([User.deleteMany({}),College.deleteMany({}),Course.deleteMany({}),CollegeCourse.deleteMany({}),CollegePlacement.deleteMany({}),CollegeFee.deleteMany({}),CampusFacility.deleteMany({})]);
const adminPass=await bcrypt.hash('Admin@123',12); await User.create({name:'System Admin',email:'admin@example.com',password:adminPass,role:'admin'});
const userPass=await bcrypt.hash('User@123',12); await User.create({name:'Demo Student',email:'student@example.com',password:userPass,role:'user',phone:'9876543210'});
const courses=await Course.insertMany(courseData.map(([courseName,courseCode,level,duration])=>({courseName,courseCode,level,duration,description:`Sample ${courseName} course for demo purposes`,careerOptions:['Technology','Business','Higher Studies']})));
const colleges=await College.insertMany(names.map((name,i)=>({name,university:`Sample University ${i+1}`,description:'Fictional demo college data for project testing.',city:['Ahmedabad','Surat','Vadodara','Rajkot'][i%4],state:'Gujarat',address:`Demo Road ${i+1}`,collegeType:['Private','Government','Autonomous','Deemed'][i%4],establishedYear:2000+i,website:'https://example.com',email:`college${i+1}@example.com`,phone:`90000000${String(i+1).padStart(2,'0')}`,campusSize:`${5+i} acres`,collegeRating:+(3.5+(i%4)*0.3).toFixed(1),eligibilityPercentage:45+i%3*5})));
const cc=[]; const fees=[]; const placements=[]; const facilities=[];
for(let i=0;i<colleges.length;i++){const c=courses[i%6];cc.push({collegeId:colleges[i]._id,courseId:c._id,eligibilityPercentage:50+i%3*5,availableSeats:60+i*5,admissionType:i%2?'Merit':'Entrance',entranceRequired:i%2===1});fees.push({collegeId:colleges[i]._id,courseId:c._id,annualTuitionFee:45000+i*5000,hostelFee:20000+i*1000,otherFees:5000,totalAnnualFee:70000+i*6000,scholarshipAvailable:i%2===0,scholarshipDetails:i%2===0?'Merit scholarship available':'No scholarship in demo data'});placements.push({collegeId:colleges[i]._id,placementRate:70+i*2,averagePackage:400000+i*50000,highestPackage:1000000+i*100000,lowestPackage:220000+i*10000,companiesVisited:30+i*5,placementYear:2026});facilities.push({collegeId:colleges[i]._id,hostel:i%2===0,library:true,computerLab:true,wifi:true,sports:i%3!==0,gym:i%2===0,cafeteria:true,transport:i%2===1,medicalFacility:i%3===0,auditorium:true,placementCell:true,campusSecurity:true});}
await CollegeCourse.insertMany(cc);await CollegeFee.insertMany(fees);await CollegePlacement.insertMany(placements);await CampusFacility.insertMany(facilities);
console.log('Seed complete. Admin: admin@example.com / Admin@123');console.log('Demo user: student@example.com / User@123');await mongoose.disconnect();}
seed().catch(e=>{console.error(e);process.exit(1)});
