import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import profileRoutes from './routes/profileRoutes.js';
import academicRoutes from './routes/academicRoutes.js';
import collegeRoutes from './routes/collegeRoutes.js';
import courseRoutes from './routes/courseRoutes.js';
import recommendationRoutes from './routes/recommendationRoutes.js';
import savedRoutes from './routes/savedRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';

const app=express();
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173',credentials:true}));
app.use(express.json({limit:'1mb'})); app.use(cookieParser());
app.get('/api/health',(req,res)=>res.json({success:true,message:'Smart College Recommendation API is running'}));
app.use('/api/auth',authRoutes); app.use('/api/profile',profileRoutes); app.use('/api/academic',academicRoutes); app.use('/api/colleges',collegeRoutes); app.use('/api/courses',courseRoutes); app.use('/api/recommendations',recommendationRoutes); app.use('/api/saved-colleges',savedRoutes); app.use('/api/admin',adminRoutes);
app.use(notFound); app.use(errorHandler);
const port=process.env.PORT||5000;
connectDB().then(()=>app.listen(port,()=>console.log(`API running at http://localhost:${port}`))).catch(err=>{console.error('Database connection failed',err);process.exit(1)});
